Try out setting the job status when a python version is not available.

diff --git a/.azure-pipelines/templates/stage-test-steps.yml b/.azure-pipelines/templates/stage-test-steps.yml
--- a/.azure-pipelines/templates/stage-test-steps.yml
+++ b/.azure-pipelines/templates/stage-test-steps.yml
@@ -1,40 +1,55 @@
+parameters:
+  ignoreFailed: false
+
 steps:
 - checkout: self
   clean: true
   submodules: true
 
 - task: UsePythonVersion@0
+  continueOnError: true
   inputs:
     versionSpec: '$(python.version)'
     architecture: 'x64'
 
 - script: |
+    echo "Failing job because $PYTHONLOCATION is not set"
+    echo "##vso[task.setvariable variable=Agent.JobStatus;]Failed"
+    exit 1
+  condition: and(eq(variables['pythonLocation'], Null), not(variables['parameters.ignoreFailed']))
+  displayName: 'Fail for missing python version'
+
+- script: |
     python -m pip install --upgrade pip setuptools
+  condition: and(succeeded(), ne(variables['pythonLocation'], Null))
   displayName: 'Update pip'
 
 - script: |
     make cythonize
-  condition: and(succeeded(), eq(variables['no_extensions'], ''))
+  condition: and(succeeded(), ne(variables['pythonLocation'], Null), eq(variables['no_extensions'], ''))
   displayName: 'Cythonize'
 
 - script: |
     pip install -r requirements/dev.txt pytest-azurepipelines
   displayName: 'Install dependencies'
+  condition: and(succeeded(), ne(variables['pythonLocation'], Null))
   env:
     FROZENLIST_NO_EXTENSIONS: '$(no_extensions)'
 
 - script: |
     pytest tests -vv --no-coverage-upload
+  condition: and(succeeded(), ne(variables['pythonLocation'], Null))
   displayName: 'pytest'
 
 - script: |
     python -m coverage xml
   displayName: 'Prepare coverage'
+  condition: and(succeeded(), ne(variables['pythonLocation'], Null))
 
 - script: |
     pip install codecov
     python -m codecov -f coverage.xml -X gcov
   displayName: 'Upload coverage reports'
-  condition: and(succeeded(), ne(variables['codecov.token'], ''))
+  condition: and(succeeded(), ne(variables['pythonLocation'], Null), ne(variables['codecov.token'], ''))
   env:
     CODECOV_TOKEN: $(codecov.token)
